version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yesod
      POSTGRES_PASSWORD: yesod_password
      POSTGRES_DB: yesod_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yesod_network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://yesod:yesod_password@postgres:5432/yesod_db
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-nextauth-secret-key-here
    depends_on:
      - postgres
    networks:
      - yesod_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  yesod_network:
    driver: bridge